<a href="https://colab.research.google.com/github/prashanthakg6/ALA/blob/main/ProblemSet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
plt.style.use('dark_background')
%matplotlib inline
import sys
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
import nltk
import gensim.downloader
from nltk.tokenize import word_tokenize

Writing the norm of v and rms of v using dot products

(a) Express ∥v∥ and rms(v) using only dot product(s). You may use 1 to represent the vector full of ones.

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], dtype = torch.float64)
print(x)
like_one = torch.ones_like(x)
print(like_one)

#compute norm
vector_norm = torch.sqrt(torch.dot(x, like_one))
print(vector_norm)

#Compute RMS
rms = vector_norm /len(x)
print(len(x))
print(rms)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 1., 1.], dtype=torch.float64)
tensor(2.4495, dtype=torch.float64)
3
tensor(0.8165, dtype=torch.float64)


 (b) For any vector v, its de-meaned or mean-centered version is the vector vm

In [ ]:
# the mean of v

x_avg = torch.mean(x)
print(x_avg)

#de-meaned value of v
x_m = x - x_avg
print(x_m)

tensor(2., dtype=torch.float64)
tensor([-1.,  0.,  1.], dtype=torch.float64)


(c) Compute avg(v)

In [ ]:
x_m_avg = torch.mean(x_m)
print(x_m_avg)

tensor(0., dtype=torch.float64)


(d) The standard deviation of the vector

In [ ]:
std_x = torch.sqrt(torch.sum(x_m**2)/len(x))
print(std_x)

tensor(0.8165, dtype=torch.float64)



(e) Compute std(cv) in terms of std(v), where c is a real constant

In [ ]:
c = 3
x_const = c * x
std_cx = torch.sqrt(torch.sum((x_const - torch.mean(x_const)) ** 2) / len(x))
print(std_cx)


tensor(2.4495, dtype=torch.float64)


(f) . Standardized version of Vector also called as z-score vector


In [ ]:
# these are z-scores values
x_s = (x_m/std_x)
print(x_s)

# avg z-scores values
avg_x_s = torch.mean(x_s)
print(avg_x_s)

# this is the mean-centered z-scores values
mean_centered_x_s = x_s - avg_x_s
print(mean_centered_x_s)

# this is std_deviation of z-scores
std_x_s = torch.sqrt(torch.sum(mean_centered_x_s)**2)/len(x_s)
print(std_x_s)

tensor([-1.2247,  0.0000,  1.2247], dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor([-1.2247,  0.0000,  1.2247], dtype=torch.float64)
tensor(0., dtype=torch.float64)


(g). The Correlation

In [ ]:
a = torch.tensor([1.0,2.0,3.0])
b = torch.tensor([4.0,5.0,6.0])
a_m = a - torch.mean(a)
print(a_m)
b_m = b - torch.mean(b)
print(b_m)

res = (torch.dot(a_m,b_m))/(torch.norm(a_m)*torch.norm(b_m))
print(res)

tensor([-1.,  0.,  1.])
tensor([-1.,  0.,  1.])
tensor(1.0000)


(h).

In [ ]:
a_s = a_m / torch.std(a)
b_s = b_m / torch.std(b)
corr2 = torch.dot(a_s, b_s) / len(a)
print(corr2)

tensor(0.6667)


---- 2nd Problem

(a) rms(a)

In [ ]:
a = torch.tensor([0.0, -1.0, -2.0], dtype=torch.float64)
b = torch.tensor([0.0,  1.0,  2.0], dtype=torch.float64)

n = len(a)
print(n)

rms_a = torch.sqrt(torch.dot(a, a)/ len(a))
print(f'RMS of a is: {rms_a}')

# -- (b). avg(b)

avg_b = torch.mean(b)
print(f'Average value of b is: {avg_b}')

# --- (c) avg(−3b).
avg_negb = torch.mean(-3 * b)
print(f'Average value of -3b is: {avg_negb}')

#--- (d).std(a)

a_centered  = a - torch.mean(a)
print(a_centered)
std_a = torch.sqrt(torch.sum(a_centered ** 2) / n)
print(f'Standard deviation of a is: {std_a}')

#-----(e).std(−3a)

neg3a = -3 * a
neg3a_centered = neg3a - torch.mean(neg3a)
std_neg3a = torch.sqrt(torch.sum(neg3a_centered ** 2)/ n)
print(f'Standard deviation of -3a is: {std_neg3a}')

#--- (f) The correlation coefficient between a and b.

a_centered = a - torch.mean(a)
b_centered = b - torch.mean(b)

#Compute numerator = dot product of centered vectors
numerator = torch.dot(a_centered, b_centered)

#Compute denominator = dot product of centered vectors
denominator = torch.sqrt(torch.dot(a_centered, a_centered)) * torch.sqrt(torch.dot(b_centered, b_centered))

corr_ab = numerator / denominator
print(f'Correalation coefficient of a and b is: {corr_ab}')

#----- (g) The distance between a and b

dis = torch.norm(a - b)
print(f'Distance between a and b is: {dis}')

#--- (h) The angle between a and b
norm_a = torch.norm(a)
norm_b = torch.norm(b)
dot_pro = torch.dot(a,b)/(norm_a * norm_b)
rad = torch.acos(dot_pro)
print(rad)
deg = torch.rad2deg(rad)
print(f'The angle between a and b is:\n')
print(deg)





3
RMS of a is: 1.2909944487358056
Average value of b is: 1.0
Average value of -3b is: -3.0
tensor([ 1.,  0., -1.], dtype=torch.float64)
Standard deviation of a is: 0.816496580927726
Standard deviation of -3a is: 2.449489742783178
Correalation coefficient of a and b is: -0.9999999999999998
Distance between a and b is: 4.47213595499958
tensor(3.1416, dtype=torch.float64)
The angle between a and b is:

tensor(180.0000, dtype=torch.float64)


In [ ]:
# 7th i

A = torch.tensor([[0,0,0,0,1],
                  [1,0,0,0,0],
                  [0,1,0,0,0],
                  [0,0,1,0,0],
                  [0,0,0,1,0]],dtype=torch.float64)

x = torch.tensor([1,2,3,4,5],dtype=torch.float64)

Ax = torch.matmul(A,x)
print(Ax)
#shows te movement of matrix in dim-0
A2 = torch.matmul(A,A)
print(A2)

A5 = torch.matmul(torch.matmul(torch.matmul(A,A2),A),A)
print(A5)

A5x = torch.matmul(A5,x)
print(A5x)

tensor([5., 1., 2., 3., 4.], dtype=torch.float64)
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], dtype=torch.float64)
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)
tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
